### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by tlvenn** [kminehart/cockroachdb-backup#1]
Thanks for this project, I was wondering if you could consider providing an Helm chart to deploy it to K8 seamlessly ?

**Comment by kminehart** [comment]
It's certainly a possibility.

I'm not sure that it's a complex enough project to warrant a helm chart, though, since it's only ~35 lines of yaml.

If there's enough demand for it I would be happy to try to merge something into https://github.com/kubernetes/charts

I'd honestly like to get around to doing AWS S3 support before that though 😓

**Comment by Rambatino** [comment]
I think helm would actually be overkill for this project - there's about 4 things you need to set and can be run with `kubectl create....` - it is just a single job that's run periodically.
